subplot(3,3,1);%三行三列第一幅
imshow(I);%显示图片
title('原图')
B=medfilt2(I,[3,3]);%中值滤波函数
subplot(3,3,2); 
imshow(B);
title('中值滤波')
C=ordfilt2(I,6,ones(3,3));%二维顺序统计滤波函数
subplot(3,3,3);
imshow(C);
title('二维顺序统计滤波')
h=fspecial('average',[3,3]);%均值滤波器
D=filter2(h,I)/255;%滤波
subplot(3,3,4); 
imshow(D)%显示图片
title('均值滤波')
h=fspecial('sobel');%边缘增强算子
D=filter2(h,I)/255;%滤波
subplot(3,3,5); 
imshow(D);%显示图片
title('sobel算子')
h=fspecial('prewitt');%边缘增强算子
D=filter2(h,I)/255;%滤波
subplot(3,3,6); 
imshow(D)%显示图片
title('Prewitt算子')
figure(2)
Q=medfilt2(I,[3,3]);%中值率波函数
subplot(2,2,1); 
imshow(Q);
title('模版大小为[3,3]的中值滤波函数')
W=medfilt2(I,[5,5]);%中值率波函数
subplot(2,2,2); 
imshow(W);
title('模版大小为[5,5]的中值滤波函数')
E=medfilt2(I,[7,7]);%中值率波函数
subplot(2,2,3);
imshow(E);
title('模版大小为[7,7]的中值滤波函数')
R=medfilt2(I,[9,9]);%中值率波函数
subplot(2,2,4);
imshow(R);
title('模版大小为[9,9]的中值滤波函数')